databases:
  cim_dev: assignment, assignment_status, campus, event, person, registration

tables:
  assignment: cim_hrdb_assignment
  assignment_status: cim_hrdb_assignmentstatus
  campus: cim_hrdb_campus
  event: cim_reg_event
  person: cim_hrdb_person
  registration: cim_reg_registration

assignment:
  id: assignment_id
  person_id: person_id
  campus_id: campus_id
  status_id: assignmentstatus_id

assignment_status:
  id: assignmentstatus_id
  description: assignmentstatus_desc

campus:
  id: campus_id
  description: campus_desc
  short_description: campus_shortDesc
  account_group_id: accountgroup_id
  region_id: region_id
  website: campus_website
  facebook_group: campus_facebookgroup
  gcx_namespace: campus_gcxnamespace
  province_id: province_id

event:
  id: event_id
  country_id: country_id
  ministry_id: ministry_id
  name: event_name
  desc_brief: event_descBrief
  desc_detail: event_descDetail
  start: event_startDate
  end: event_endDate
  reg_start: event_regStart
  reg_end: event_regEnd
  website: event_website
  email_text: event_emailConfirmText
  price: event_basePrice
  deposit: event_deposit
  email: event_contactEmail
  price_text: event_pricingText
  on_home_page: event_onHomePage
  allow_cash: event_allowCash

person:
  id: person_id
  first_name: person_fname
  last_name: person_lname
  legal_first_name: person_legal_fname
  legal_last_name: person_legal_lname
  phone: person_phone
  email: person_email
  address: person_addr
  city: person_city
  province_id: province_id
  postal_code: person_pc
  gender_id: gender_id
  local_phone: person_local_phone
  local_address: person_local_addr
  local_city: person_local_city
  local_postal_code: person_local_pc
  local_province_id: person_local_province_id
  cell_phone: cell_phone
  local_valid_until: local_valid_until
  title_id: title_id
  country_id: country_id
  local_country_id: person_local_country_id
  middle_name: person_mname

registration:
  id: registration_id
  event_id: event_id
  person_id: person_id
  date: registration_date
  confirm_num: registration_confirmNum
  status_id: registration_status
  balance: registration_balance
