databases:
  cim_dev: event

tables:
  event: cim_reg_event

event:
  id: event_id
  country: country_id
  ministry: ministry_id
  name: event_name
  desc_brief: event_descBrief
  desc_detail: event_descDetail
  start: event_startDate
  end: event_endDate
  reg_start: event_regStart
  reg_end: event_regEnd
  website: event_website
  email_text: event_emailConfirmText
  price: event_basePrice
  deposit: event_deposit
  email: event_contactEmail
  price_text: event_pricingText
  on_home_page: event_onHomePage
  allow_cash: event_allowCash
